name: Release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to release
        required: true

jobs:
  call-release-workflow:
    uses: Gilead-BioStats/gsm.utils/.github/workflows/r_releaser.yaml@main
    with:
      tag: ${{ github.event.release.tag_name || inputs.tag }}
    secrets: inherit
